server:
  port: 88
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.77.101:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: thirdparty_route
          uri: lb://mall-thirdparty
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://mall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/admin/$\{segment}

        - id: mall_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com

        - id: product_item_route
          uri: lb://mall-product
          predicates:
            - Host=item.mall.com

        - id: product_site_route
          uri: lb://mall-product
          predicates:
            - Host=**.mall.com
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
main:
  web-application-type: reactive
