mall.mq.connection.host=${RABBITMQ_HOST:192.168.77.100}
mall.mq.connection.port=${RABBITMQ_PORT:5672}
mall.mq.connection.username=${RABBITMQ_USERNAME:guest}
mall.mq.connection.password=${RABBITMQ_PASSWORD:guest}

