server:
  port: 20000
spring:
  application:
    name: mall-auth
    admin:
      enabled: false
  jmx:
    enabled: false
  redis:
    host: ${REDIS_HOST:192.168.77.100}
    port: ${REDIS_PORT:6379}
  thymeleaf:
    cache: false

mall:
  session:
    enabled: true
  auth:
    weibo:
      appKey: 4239681478
      appSecret: 632f00612cb695abd9ddbae000204dec
