server:
  port: 16000
spring:
  application:
    name: mall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.77.101:8848
        service: mall-cart
  redis:
    host: 192.168.77.100
    port: 6379
  thymeleaf:
    cache: false

mall:
  session:
    enabled: true

