server:
  port: 16000
spring:
  application:
    name: mall-cart
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:192.168.77.101:8848}
        service: mall-cart
  redis:
    host: ${REDIS_HOST:192.168.77.100}
    port: ${REDIS_PORT:6379}
  thymeleaf:
    cache: false

mall:
  session:
    enabled: true

